baseURL = "https://sykomaniac.github.io/"
title = "Sykomaniac :: Home"
theme = ["hugo-orbit-theme", "m10c"]
paginate = 5
disableRSS = true
disableSitemap = true
disable404 = true

[params]
  author = "Ashley Sykes"
  description = "A proud dad, passionate Software Engineer and football fanatic."
  avatar = "me-small.png"
  styles = "styles-6.css" #C V style

  [[params.social]]
    name = "github"
    url = "https://github.com/Sykomaniac"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/ashsykes15"

  # Green theme
  [params.style]
    darkestColor = "#4B6A78"
    darkColor = "#253031"
    primaryColor = "#dad865"
    lightColor = "#96a879"
    lightestColor = "#fff"

  # Profile section
  [params.profile]
      name = "Ashley Sykes"
      tagline = "Full Stack Developer"
      avatar = "me-small.png"

  # Contact section
  [params.contact]
      enable = true

      [[params.contact.list]]
      class = "email"
      icon = "fa-envelope"
      url = "mailto: ashley.sykes@gmail.com"
      title = "ashley.sykes@gmail.com"

      [[params.contact.list]]
      class = "phone"
      icon = "fa-phone"
      url = "tel:+447975732684"
      title = "+44797 573 2684"

      [[params.contact.list]]
      class = "website"
      icon = "fa-globe"
      url = "//sykomaniac.github.io"
      title = "sykomaniac.github.io"

      [[params.contact.list]]
      class = "linkedin"
      icon = "fa-linkedin"
      url = "//linkedin.com/in/ashsykes"
      title = "linkedin/ashsykes"

      [[params.contact.list]]
      class = "github"
      icon = "fa-github"
      url = "//github.com/sykomaniac"
      title = "github.com/sykomaniac"

      [[params.contact.list]]
      class = "twitter"
      icon = "fa-twitter"
      url = "//twitter.com/ashsykes15"
      title = "@ashsykes15"

  # Education section
  [params.education]
      enable = true
      title = "Education"

      [[params.education.list]]
      college = "University of Leeds"
      degree = "1st Class with Honors BSc in Computer Science"
      dates = "2006 - 2009"

      [[params.education.list]]
      college = "West Leeds Sixth Form College"
      degree = "3 B's at A-Level in English Language, English Literature and Sports Science"
      dates = "2004 - 2006"

      [[params.education.list]]
      college = "West Leeds High School"
      degree = "10 A - B GCSE's English, Maths, Science etc"
      dates = "1999 - 2004"

  # Languages section
  [params.language]
      enable = false
      title = "Languages"

  # Interests section
  [params.interests]
      enable = true
      title = "Interests"

      [[params.interests.list]]
      interest = "Being a dad"

      [[params.interests.list]]
      interest = "Playing with software projects"

      [[params.interests.list]]
      interest = "Football"

      [[params.interests.list]]
      interest = "Ballroom dancing"

  # Summary section
  [params.summary]
      enable = true
      icon = "fa-user"
      title = "Personal Summary"
      summary = "I am an incredibly hard working individual with a vast amount of technical experience and a real passion for software development. I thoroughly enjoy working on and resolving difficult problems in the most elegant way possible. Beyond software development I am a proud dad and a football enthusiast."

  # Experiences section
  [params.experiences]
      enable = false
      icon = "fa-briefcase"
      title = "Experiences"

      [[params.jobs.list]]
      position = "Technical Expert"
      dates = "2019 - Present"
      company = "Asda Stores Limited, Leeds, UK"
      details = "**Describe your role here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo.\n\n Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo."

      [[params.jobs.list]]
      position = "Senior Software Engineer"
      dates = "2018 - 2019"
      company = "Edgetic Ltd, Leeds, UK"
      details = "**Describe your role here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo.\n\n Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo."

      [[params.jobs.list]]
      position = "Senior Software Engineer"
      dates = "2015 - 2017"
      company = "Asda Stores Limited, Leeds, UK"
      details = "**Describe your role here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem."

      [[params.jobs.list]]
      position = "Senior Software Engineer"
      dates = "2009 - 2015"
      company = "X-Lab Ltd, Leeds, UK"
      details = "**Describe your role here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem."

  # Projects section
  [params.projects]
      enable = true
      icon = "fa-archive"
      title = "Projects"
      intro = ""

      [[params.projects.list]]
      title = "Flutter"
      url = "https://sykomaniac.github.io/posts/WIP_flutter/"
      tagline = "A React Native developers view of FLutter."

      [[params.projects.list]]
      title = "Java GraphQL"
      url = "https://sykomaniac.github.io/posts/20190531_graphql/"
      tagline = "An up to date walkthrough of using Spring Boot to work with GraphQL and MongoDB."

      [[params.projects.list]]
      title = "Me"
      url = "https://github.com/aerohub/hugo-me-theme"
      tagline = "A simple responsive Hugo setup for my personal site."

  # Skills section
  [params.skills]
      enable = true
      icon = "fa-rocket"
      title = "Skills & Proficiency"

      [[params.skills.list]]
      skill = "Python & Django"
      level = "98%"
              
      [[params.skills.list]]
      skill = "Backend languages (Node.js, .NET, Java, Python & Golang)"
      level = "98%"

      [[params.skills.list]]
      skill = "Frontend languages (React, Knockout.js, Backbone.js, Ember.js)"
      level = "98%"

      [[params.skills.list]]
      skill = "Mobile Development languages (React Native, Flutter)"
      level = "95%"

      [[params.skills.list]]
      skill = "Web technologies (CSS, HTML, Sass etc)"
      level = "98%"

      [[params.skills.list]]
      skill = "RDBMS (MSSQL, MariaDB etc)"
      level = "98%"

      [[params.skills.list]]
      skill = "NoSQL (MongoDB, Cassandra, InfluxDB etc)"
      level = "95%"

      [[params.skills.list]]
      skill = "Containerisation tooling (Docker, Docker Compose, Kubernetes, Helm, Draft)"
      level = "90%"

      [[params.skills.list]]
      skill = "SCM, CI & CD tooling (Git, Jenkins etc)"
      level = "98%"

      [[params.skills.list]]
      skill = "SDLC (Scrum, Kanban, Lean, Prince 2)"
      level = "98%"

  # Footer section
  [params.footer]
      copyright = "Ashley Sykes"