baseURL = "https://sykomaniac.github.io/"
title = "Sykomaniac :: Home"
theme = ["hugo-orbit-theme", "m10c"]
paginate = 5
disableRSS = true
disableSitemap = true
disable404 = true

[params]
  author = "Ashley Sykes"
  description = "A proud dad, passionate Software Engineer and football fanatic."
  avatar = "me-small.png"
  styles = "styles-6.css" #C V style

  [[params.social]]
    name = "github"
    url = "https://github.com/Sykomaniac"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/ashsykes15"

  # Green theme
  [params.style]
    darkestColor = "#4B6A78"
    darkColor = "#253031"
    primaryColor = "#dad865"
    lightColor = "#96a879"
    lightestColor = "#fff"

  # Profile section
  [params.profile]
      name = "Ashley Sykes"
      tagline = "Full Stack Developer"
      avatar = "me-small.png"

  # Contact section
  [params.contact]
      enable = true

      [[params.contact.list]]
      class = "email"
      icon = "fa-envelope"
      url = "mailto: ashley.sykes@gmail.com"
      title = "ashley.sykes@gmail.com"

      [[params.contact.list]]
      class = "phone"
      icon = "fa-phone"
      url = "tel:+447975732684"
      title = "+44797 573 2684"

      [[params.contact.list]]
      class = "website"
      icon = "fa-globe"
      url = "//sykomaniac.github.io"
      title = "sykomaniac.github.io"

      [[params.contact.list]]
      class = "linkedin"
      icon = "fa-linkedin"
      url = "//linkedin.com/in/ashsykes"
      title = "linkedin/ashsykes"

      [[params.contact.list]]
      class = "github"
      icon = "fa-github"
      url = "//github.com/sykomaniac"
      title = "github.com/sykomaniac"

      [[params.contact.list]]
      class = "twitter"
      icon = "fa-twitter"
      url = "//twitter.com/ashsykes15"
      title = "@ashsykes15"

  # Education section
  [params.education]
      enable = true
      title = "Education"

      [[params.education.list]]
      college = "University of Leeds"
      degree = "1st Class with Honors BSc in Computer Science"
      dates = "2006 - 2009"

      [[params.education.list]]
      college = "West Leeds Sixth Form College"
      degree = "3 B's at A-Level in English Language, English Literature and Sports Science"
      dates = "2004 - 2006"

      [[params.education.list]]
      college = "West Leeds High School"
      degree = "10 A - B GCSE's English, Maths, Science etc"
      dates = "1999 - 2004"

  # Languages section
  [params.language]
      enable = false
      title = "Languages"

  # Interests section
  [params.interests]
      enable = true
      title = "Interests"

      [[params.interests.list]]
      interest = "Being a dad"

      [[params.interests.list]]
      interest = "Playing with software projects"

      [[params.interests.list]]
      interest = "Football"

      [[params.interests.list]]
      interest = "Ballroom dancing"

  # Summary section
  [params.summary]
      enable = true
      icon = "fa-user"
      title = "Personal Summary"
      summary = "I am an incredibly hard working individual with a vast amount of technical experience and a real passion for software development. I thoroughly enjoy working on and resolving difficult problems in the most elegant way possible. Beyond software development I am a proud dad and a football enthusiast."

  # Experiences section
  [params.experiences]
      enable = true
      icon = "fa-briefcase"
      title = "Experiences"

      [[params.jobs.list]]
      position = "Technical Expert"
      dates = "2019 - Present"
      company = "Asda Stores Limited, Leeds, UK"

      [[params.jobs.list]]
      position = "Senior Software Engineer"
      dates = "2018 - 2019"
      company = "Edgetic Ltd, Leeds, UK"
      details = "Edgetic is an exciting start-up researching the Kubernetes scheduler and how to improve its power efficiency through machine learning and big data. Whilst at Edgetic I worked on the core scheduling mechanism which built upon the extender model provided by Kubernetes and made use of agents to collate key data metrics. The scheduler was written using Golang and leveraged a number of technologies such as, Redis for caching calculations, InfluxDB for storing time based metrics, low-level performance tracing libraries e.g. eBPF, cgroups and Perf for collecting performance data and other tools. Whilst working on the design and implementation of the scheduler I also built a number of bespoke tools using Python (mainly NumPy and pandas) to help analyse the collected data and build 2nd/3rd order polynomial models for power efficiency analysis. I also built a number of tools to help with research tasks, for example, I created a VM migration tool written in Python, a Golang service to generate workloads using industry standard benchmarking tools e.g. HiBench, sysbench, TeraSort and many others."

      [[params.jobs.list]]
      position = "Senior Software Engineer"
      dates = "2015 - 2017"
      company = "Asda Stores Limited, Leeds, UK"
      details = "My initial role within Asda required me to primarily work in the Mobile Apps space. After being with Asda for a year I was asked to extend my remit (due to the excellent work I had delivered) to also include general application development (mainly ASP.NET projects). During my time at Asda I worked on a multitude of colleague focused applications, each application would follow a similar design pattern – an Angular.JS Ionic application that communicated with a RESTful backend service (either ASP.NET Web API or Express.JS) which in turn communicated with a data store (either MSSQL or MongoDB). My other responsibilities with Asda included up-skilling colleagues in the use of CI/CD tooling (mainly Git, Jenkins, Ansible and OneOps), advocating and driving adoption of SCRUM and Lean principles and practices, recruiting new team members and tutoring junior members in the team. Whilst at Asda I also joined the Colleague Voice team to try and improve engagement between the Asda business and development teams."

      [[params.jobs.list]]
      position = "Senior Software Engineer"
      dates = "2009 - 2015"
      company = "X-Lab Ltd, Leeds, UK"
      details = "During my time at X-Lab I graduated from junior developer to senior developer over a 6 year period. My main responsibility required me to work on a national solution for use by the NHS to transfer test requests and results between pathology labs utilising different LIMS (Laboratory Information Management System). A particular highlight of my time at X-Lab required me to design, prototype and build a replacement for the Microsoft BizTalk integration engine. To achieve this we built upon the ESB pattern, developing a number of bespoke components in C# and Apache Camel. My day to day activities included developing, supporting and maintaining a large ASP.NET MVC codebase, defining, implementing and enhancing working practices - ranging from the introduction of Git, adopting Team City and Octopus Deploy for CI/CD, implementing SCRUM, assisting in sales meetings, recruiting new team members, line managing other developers and tutoring junior members of the team. Whilst at X-Lab I also worked on a number of other systems such as Patient Pathway Manager (a Backbone.js SPA for use in Leeds Teaching Hospital wards to display patient information) and ScreenTalk (a multi locale ASP.NET MVC app to help women from ethnically diverse backgrounds better understand cervical cancer screening)."

  # Projects section
  [params.projects]
      enable = true
      icon = "fa-archive"
      title = "Projects"
      intro = ""

      [[params.projects.list]]
      title = "Flutter"
      url = "https://sykomaniac.github.io/posts/WIP_flutter/"
      tagline = "A React Native developers view of FLutter."

      [[params.projects.list]]
      title = "Java GraphQL"
      url = "https://sykomaniac.github.io/posts/20190531_graphql/"
      tagline = "An up to date walkthrough of using Spring Boot to work with GraphQL and MongoDB."

      [[params.projects.list]]
      title = "Me"
      url = "https://github.com/Sykomaniac/sykomaniac.github.io"
      tagline = "A simple responsive Hugo setup for my personal site."

  # Skills section
  [params.skills]
      enable = true
      icon = "fa-rocket"
      title = "Skills & Proficiency"

      [[params.skills.list]]
      skill = "Python & Django"
      level = "98%"
              
      [[params.skills.list]]
      skill = "Backend languages (.NET, Java, Python, Golang, Node.js)"
      level = "98%"

      [[params.skills.list]]
      skill = "Frontend languages (React, Angular.js, Knockout.js, Backbone.js, Ember.js)"
      level = "98%"

      [[params.skills.list]]
      skill = "Mobile Development languages (React Native, Flutter)"
      level = "95%"

      [[params.skills.list]]
      skill = "Web technologies (CSS3, HTML5, Sass, Less, Stylus etc)"
      level = "98%"

      [[params.skills.list]]
      skill = "RDBMS (MSSQL, MariaDB etc)"
      level = "98%"

      [[params.skills.list]]
      skill = "NoSQL (MongoDB, Cassandra, InfluxDB etc)"
      level = "95%"

      [[params.skills.list]]
      skill = "Containerisation tooling (Docker, Docker Compose, Kubernetes, Helm, Draft, etc)"
      level = "90%"

      [[params.skills.list]]
      skill = "SCM, CI & CD tooling (Git, Jenkins, Ansible, Vagrant etc)"
      level = "98%"

      [[params.skills.list]]
      skill = "SDLC (Scrum, Kanban, Lean, Prince 2)"
      level = "98%"

  # Footer section
  [params.footer]
      copyright = "Ashley Sykes"